# Generated by Django 4.0.3 on 2022-04-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userextension_avatar_alter_userextension_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='avatar',
            field=models.ImageField(upload_to='avatar'),
        ),
    ]
