# Generated by Django 4.0.3 on 2022-03-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_publicacion', models.DateTimeField()),
                ('titulo', models.CharField(max_length=20)),
                ('publicacion', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InfoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('ocupacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('caracteristicas', models.TextField(max_length=50)),
                ('creadora', models.CharField(max_length=20)),
            ],
        ),
    ]
