# Generated by Django 4.0.3 on 2022-03-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_usuario_delete_infousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='caracteristicas',
            field=models.TextField(max_length=100),
        ),
    ]
