# Generated by Django 4.0.3 on 2022-03-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_remove_blog_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publicacion',
            field=models.TextField(max_length=300),
        ),
    ]
