# Generated by Django 4.0.3 on 2022-04-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogs_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='resumen',
            field=models.CharField(max_length=100),
        ),
    ]
