# Generated by Django 4.0.3 on 2022-04-18 19:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogs_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='subtitulo',
            field=ckeditor.fields.RichTextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='titulo',
            field=ckeditor.fields.RichTextField(blank=True, max_length=30, null=True),
        ),
    ]
