# Generated by Django 4.0.3 on 2022-03-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='InfoUsuario',
        ),
        migrations.DeleteModel(
            name='Tienda',
        ),
    ]
